// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-wx-YO_fN7lJTXSYPDSrhfOCXo-Xq1N4',
    appId: '1:1072952323658:web:cce64edd7bc0aa9a5d80b3',
    messagingSenderId: '1072952323658',
    projectId: 'reruiterupdated',
    authDomain: 'reruiterupdated.firebaseapp.com',
    storageBucket: 'reruiterupdated.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgXNSMo9BtbJYTYLvVzeDTqrp9ZW_NSro',
    appId: '1:1072952323658:android:e1ebe7096723b37b5d80b3',
    messagingSenderId: '1072952323658',
    projectId: 'reruiterupdated',
    storageBucket: 'reruiterupdated.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOEzywGRdf61dSfirh8oxGy6waNv0iWpk',
    appId: '1:1072952323658:ios:332418fa3e4ef0b95d80b3',
    messagingSenderId: '1072952323658',
    projectId: 'reruiterupdated',
    storageBucket: 'reruiterupdated.appspot.com',
    iosBundleId: 'com.example.recruiter',
  );
}
